// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv1mDqdco8qkM_SxRrE1IrhnCtlVKYxRo',
    appId: '1:754684332828:web:254a58454fd975761ec8d9',
    messagingSenderId: '754684332828',
    projectId: 'takash196',
    authDomain: 'takash196.firebaseapp.com',
    storageBucket: 'takash196.firebasestorage.app',
    measurementId: 'G-TG69DJ953L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjWyQFyLFJFAU2BLEtalW3DbFdFuY5N4',
    appId: '1:754684332828:android:30a6066d36655c241ec8d9',
    messagingSenderId: '754684332828',
    projectId: 'takash196',
    storageBucket: 'takash196.firebasestorage.app',
  );
}
